"use client";

import { useState } from "react";
import { ArrowRight, Building2, Check, Clock3, CreditCard, Download, FileImage, FileText, FolderOpen, LockKeyhole, MessageSquare, Plus, Receipt, ShieldCheck, Upload, UserRound } from "lucide-react";
import type { WorkspaceTab } from "./case-panels";
import { Button } from "./workspace-ui";

const emptyTabs: WorkspaceTab[] = ["overview", "evidence", "messages", "finances", "escrow", "activity"];

function EmptyOverview({ onCreate, onTab, onCases }: { onCreate: () => void; onTab: (tab: WorkspaceTab) => void; onCases: () => void }) {
  return <>
    <div className="tenant-empty-progress">{["Case started", "Evidence added", "Notice prepared", "Rent protected", "Resolution"].map((label) => <span key={label}>{label}</span>)}</div>
    <section className="tenant-no-case-cta"><span><FolderOpen size={23} /></span><h2>No case selected</h2><p>Create a new case to begin protecting your rent, or select an existing case from My cases to continue where you left off.</p><div><Button variant="primary" icon={Plus} onClick={onCreate}>Create a case</Button><Button onClick={onCases}>View my cases</Button></div></section>
    <div className="tenant-empty-overview-grid"><section><h3>Issue summary</h3><div className="tenant-skeleton-lines"><i /><i /><i /></div><dl><div><dt>Started</dt><dd /></div><div><dt>Category</dt><dd /></div><div><dt>Reported to</dt><dd /></div></dl><button onClick={onCreate}>Populated after case creation <ArrowRight size={13} /></button><div className="tenant-empty-overview-section"><div><h3>Evidence</h3><p>Photos, documents, and records will appear here</p></div><button onClick={() => onTab("evidence")}>Upload evidence →</button><div className="tenant-placeholder-gallery"><span><FileImage size={19} /></span><span><FileText size={19} /></span><span><Plus size={19} /></span></div></div><div className="tenant-empty-overview-section"><h3>Building details</h3><div className="tenant-property-placeholder"><Building2 size={22} />Property photo</div></div></section><aside><section><div><h3>Rent escrow</h3><span>Not active</span></div><small>DISPUTED AMOUNT</small><strong>–</strong><p>Rent period to be determined</p><Button disabled icon={LockKeyhole}>Protect rent in escrow</Button><p>Available once a case is created and your rent dispute is documented.</p></section><section><h3>Release requirements</h3>{["Required notice prepared", "Evidence package organized", "Landlord response received", "Settlement or order documented"].map((label) => <p key={label}><i />{label}</p>)}</section><section><h3>Recent activity</h3><div className="tenant-skeleton-lines"><i /><i /><i /></div><button onClick={() => onTab("activity")}>Activity will appear here →</button></section></aside></div>
  </>;
}

function EmptyEvidence({ onCreate }: { onCreate: () => void }) {
  const [filter, setFilter] = useState<"all" | "photos" | "documents" | "messages">("all");
  const guidance = [[FileImage, "Photos", "Conditions, damage, temperature readings"], [FileText, "Documents", "Lease, repair requests, inspection reports"], [MessageSquare, "Messages", "Texts, emails, or chats with your landlord"], [Receipt, "Receipts & records", "Payments, service calls, 311 complaints"]] as const;
  return <section className="tenant-empty-evidence"><div className="tenant-empty-section-heading"><div><h2>Evidence gallery</h2><p>Upload photos, documents, and records to support your case.</p></div><Button variant="primary" icon={Upload} onClick={onCreate}>Create case to upload</Button></div><div className="tenant-evidence-controls"><div>{(["all", "photos", "documents", "messages"] as const).map((value) => <button key={value} aria-pressed={filter === value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div><div className="tenant-evidence-search"><input type="search" aria-label="Search evidence" placeholder="Search evidence" disabled /><select aria-label="Sort evidence" disabled><option>Newest first</option></select></div></div><div className="tenant-evidence-drop"><span><Upload size={22} /></span><h3>No evidence uploaded yet</h3><p>Create a case first, then choose a supported file from your device.</p><Button variant="primary" onClick={onCreate}>Create a case first</Button><small>Supported file types</small><div>{["PDF", "JPG / PNG", "WEBP"].map((type) => <i key={type}>{type}</i>)}</div><em>Maximum file size: 5 MiB per file</em></div><h3 className="tenant-guidance-heading">What to include as evidence</h3><div className="tenant-evidence-guidance">{guidance.map(([Icon, title, copy]) => <article key={title}><span><Icon size={18} /></span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><p className="tenant-encryption-note">No evidence uploaded yet · Supported uploads are saved to your case record.</p></section>;
}

function EmptyMessages({ onCreate }: { onCreate: () => void }) {
  return <div className="tenant-empty-messages"><section className="tenant-thread-list"><div><h3>THREADS</h3><span>0</span></div><article><strong>Thread title</strong><p>Message preview will appear here...</p></article><article><strong>Thread title</strong><p>Message preview will appear here...</p></article><div className="tenant-thread-empty"><span><MessageSquare size={20} /></span><h3>No conversations yet</h3><p>Create a case first to add its landlord or property manager contact.</p><Button variant="primary" icon={Plus} onClick={onCreate}>Create a case first</Button></div></section><section className="tenant-conversation-empty"><header><span><UserRound size={18} /></span><div><strong>No contact added</strong><p>Create a case to add a landlord or property manager</p></div><small>Select a thread</small></header><div><span><MessageSquare size={24} /></span><h3>No messages yet</h3><p>Once a case has a landlord or property manager contact, its conversation will appear here. Messages are timestamped and saved with the case.</p><Button variant="primary" icon={Plus} onClick={onCreate}>Create a case first</Button></div><footer aria-disabled="true">Create a case to start messaging...</footer></section><aside className="tenant-notice-empty"><div><h3>FORMAL NOTICE</h3><span>Not started</span></div><section><span><FileText size={20} /></span><h3>No draft yet</h3><p>A message draft is prepared from the case details for the tenant to review before sending.</p><ol><li>Create your case</li><li>Upload evidence or photos</li><li>Review the message before sending</li></ol></section><small>You review and approve each outbound message.</small></aside></div>;
}

function EmptyFinances({ onCreate }: { onCreate: () => void }) {
  return <section className="tenant-empty-finances"><div className="tenant-empty-section-heading"><div><h2>Finances</h2><p>Load verified banking context, record case expenses, and review simulated escrow activity.</p></div><Button icon={Plus} disabled>Add expense</Button></div><dl className="tenant-finance-metrics"><div><dt>Simulated escrow</dt><dd>–</dd><small>Available after a case is created</small></div><div><dt>Documented impact</dt><dd>$0.00</dd><small>No case expenses recorded</small></div><div><dt>Monthly rent</dt><dd>–</dd><small>Entered during case setup</small></div></dl><div className="tenant-finance-grid"><section><h3>Linked payment account</h3><p>Server-verified sandbox banking context for a case</p><div className="tenant-bank-card"><span>YOUR BANK<br />ACCOUNT TYPE</span><CreditCard size={23} /><strong>•••• •••• •••• ••••</strong><small>ACCOUNT HOLDER<br />–</small><em>VERIFIED BALANCE&nbsp;&nbsp; --</em></div><div className="tenant-connect-bank"><h3>Load financial profile</h3><p>Create a case first. The server can then load its configured demo fixture or Nessie sandbox profile; this does not move real funds.</p><Button variant="primary" onClick={onCreate}>Create a case first</Button></div></section><section className="tenant-safeguards"><h3>Authorization safeguards</h3><p>The application records each requested financial action.</p>{[["Tenant starts funding", "A tenant action is required to create simulated escrow."], ["Amount shown before approval", "The case amount is shown before release confirmation."], ["Server policy checks", "Trusted case, destination, amount, and network data are checked server-side."], ["Recorded settlement context", "Simulated USD or optional XRPL Testnet activity is saved to the case audit trail."]].map(([title, copy]) => <div key={title}><Check size={15} /><span><strong>{title}</strong><small>{copy}</small></span></div>)}</section></div><section className="tenant-empty-expenses"><h3>Expenses and financial impact</h3><p>Case expenses are recorded with their date, category, amount, and source.</p><div><span><Receipt size={21} /></span><h3>No expenses recorded yet</h3><p>Create a case first, then add relevant receipts or expense details to its financial record.</p><Button variant="primary" icon={Plus} onClick={onCreate}>Create a case first</Button></div></section></section>;
}

function EmptyEscrow({ onCreate }: { onCreate: () => void }) {
  return <div className="tenant-empty-escrow"><div className="tenant-empty-escrow-primary"><section className="tenant-escrow-setup"><header><span><LockKeyhole size={18} /></span><div><h2>Escrow not configured</h2><p>Create a case first to configure simulated funding</p></div></header><div className="tenant-money-flow"><div><h3>Money flow</h3><small>SIMULATED PATH</small></div><div><article><CreditCard size={20} /><p>No case financial profile</p><Button onClick={onCreate}>Create a case first</Button></article><ArrowRight size={21} /><article><h3>SIMULATED ESCROW</h3><p>Add rent details during case setup</p><small>Release requires tenant approval</small></article></div></div><ol>{[["Add rent details", "Enter your monthly rent amount and the disputed period"], ["Load a financial profile", "Load the configured demo fixture or Nessie sandbox context"], ["Complete case requirements", "Prepare notice, organize evidence, and document repair status"]].map(([title, copy], index) => <li key={title}><span>{index + 1}</span><div><strong>{title}</strong><p>{copy}</p></div><button onClick={onCreate}>Create case</button></li>)}</ol><Button disabled icon={LockKeyhole}>Fund escrow - create a case first</Button><p className="tenant-funding-note"><ShieldCheck size={14} />Simulated funding is recorded on the case. Any release requires tenant confirmation and server policy checks.</p></section><section className="tenant-beneficiary-empty"><h2>Beneficiary and reference</h2><p>These details are generated from your case and lease information once configured.</p><div><Building2 size={23} />Property photo will appear after setup</div></section><section className="tenant-settlement-empty"><h2>Settlement context</h2><p>Facts relevant to any future release decision will appear here as your case progresses.</p><div><FileText size={22} /><strong>No facts recorded yet</strong><span>Case evidence, temperature logs, notices, and repair status will populate automatically.</span></div></section></div><aside><section><h3>Release requirements <span>0 of 4</span></h3>{["Simulated rent set aside", "Repair reported complete", "After-repair evidence verified", "Tenant confirms the resolution"].map((item) => <p key={item}><i />{item}</p>)}</section><section><h3>Policy checks</h3>{["Case ownership", "Financial profile binding", "Case eligibility", "Tenant approval"].map((item) => <p key={item}><span>{item}</span><small>Not started</small></p>)}</section><section><h3><ShieldCheck size={16} />How funding is recorded</h3><p>This prototype records simulated USD escrow on the case. Optional settlement uses valueless XRPL Testnet assets only after server policy checks and tenant confirmation.</p></section></aside></div>;
}

function EmptyActivity({ onCreate }: { onCreate: () => void }) {
  const [filter, setFilter] = useState<"all" | "evidence" | "messages" | "finances" | "system">("all");
  return <section className="tenant-activity"><div className="tenant-activity-heading"><div><h2>Case activity</h2><p>Every action you and RentEscrow take will be timestamped and recorded here — evidence uploads, messages, financial steps, and system events.</p></div><Button icon={Download} disabled>Export audit log</Button></div><div className="tenant-activity-controls"><div className="segmented-control" aria-label="Filter case activity">{(["all", "evidence", "messages", "finances", "system"] as const).map((value) => <button key={value} aria-pressed={filter === value} className={filter === value ? "selected" : ""} onClick={() => setFilter(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div><span><ShieldCheck size={15} />Audit trail starts with a case</span></div><div className="tenant-activity-layout"><section className="tenant-activity-stream"><div className="tenant-activity-stream-head"><h3>Activity stream</h3><span>No {filter === "all" ? "" : `${filter} `}events recorded</span></div><div className="tenant-activity-empty"><span><Clock3 size={24} /></span><h3>No activity yet</h3><p>Create a case first. Evidence uploads, messages, financial steps, and system actions will then appear here with their recorded timestamps.</p><div><Button variant="primary" onClick={onCreate}>Create a case</Button><Button onClick={onCreate}>Create case to upload</Button></div></div></section><aside className="tenant-audit-sidebar"><section><h3>Audit summary</h3><dl><div><dt>Total recorded events</dt><dd>–</dd></div><div><dt>Evidence changes</dt><dd>–</dd></div><div><dt>Financial actions</dt><dd>–</dd></div></dl><div className="tenant-audit-intact"><ShieldCheck size={17} /><div><strong>No case history yet</strong><span>Recording begins at case creation</span></div></div></section><section className="tenant-permanent-record"><h3><LockKeyhole size={16} />Case activity record</h3><p>Recorded case actions include timestamps so you can review what happened and when.</p></section></aside></div></section>;
}

export function TenantEmptyWorkspace({ tab, onTab, onCreate, onCases }: { tab: WorkspaceTab; onTab: (tab: WorkspaceTab) => void; onCreate: () => void; onCases: () => void }) {
  return <section className="tenant-empty-workspace">
    <div className="tenant-case-breadcrumb"><button type="button" onClick={onCases}>My cases</button><span>/</span><span>No case selected</span></div>
    <div className="case-header"><div><div className="tenant-title-row"><h1>No case selected</h1><span className="tenant-empty-status">Not started</span></div><div className="case-location"><span>No case selected</span><span className="location-divider" /><span>Create or select a case to continue</span></div></div><Button icon={tab === "overview" ? Plus : Download} onClick={tab === "overview" ? onCreate : undefined} disabled={tab !== "overview"}>{tab === "overview" ? "New case" : "Export case"}</Button></div>
    <div className="case-tabs" role="tablist" aria-label="Case sections">{emptyTabs.map((item, index) => <button key={item} role="tab" id={`empty-tab-${item}`} aria-selected={tab === item} aria-controls={`empty-panel-${item}`} tabIndex={tab === item ? 0 : -1} className={tab === item ? "active" : ""} onClick={() => onTab(item)} onKeyDown={(event) => { let next: number | null = null; if (event.key === "ArrowRight") next = (index + 1) % emptyTabs.length; if (event.key === "ArrowLeft") next = (index + emptyTabs.length - 1) % emptyTabs.length; if (event.key === "Home") next = 0; if (event.key === "End") next = emptyTabs.length - 1; if (next !== null) { event.preventDefault(); onTab(emptyTabs[next]); document.getElementById(`empty-tab-${emptyTabs[next]}`)?.focus(); } }}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    <div className="tenant-empty-content" role="tabpanel" id={`empty-panel-${tab}`} aria-labelledby={`empty-tab-${tab}`} tabIndex={0}>{tab === "overview" ? <EmptyOverview onCreate={onCreate} onTab={onTab} onCases={onCases} /> : tab === "evidence" ? <EmptyEvidence onCreate={onCreate} /> : tab === "messages" ? <EmptyMessages onCreate={onCreate} /> : tab === "finances" ? <EmptyFinances onCreate={onCreate} /> : tab === "escrow" ? <EmptyEscrow onCreate={onCreate} /> : <EmptyActivity onCreate={onCreate} />}</div>
  </section>;
}
